apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-test-api
  labels:
    app.kubernetes.io/name: job-test-api
    app.kubernetes.io/instance: job-test-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: job-test-api
      app.kubernetes.io/name: job-test-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: job-test-api
        app.kubernetes.io/name: job-test-api
        app.kubernetes.io/component: deployment.yaml        
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["sh", "-c", "sleep 400"]
        env:
          - name: SOMETHING
            value: "2"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-test-api-db-migration
  labels:
    app.kubernetes.io/name: job-test-api
    app.kubernetes.io/instance: job-test-api
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  template:
    spec:
      containers:
      - name: job-test-api-db-migrate
        image: busybox
        command: ["sh", "-c", "sleep 5"]
        resources: {}
      restartPolicy: Never
