apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  labels:
    app.kubernetes.io/name: test-api
    app.kubernetes.io/instance: test-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-api
      app.kubernetes.io/name: test-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test-api
        app.kubernetes.io/name: test-api
        app.kubernetes.io/component: deployment.yaml        
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["sh", "-c", "sleep 400"]
        env:
          - name: SOMETHING
            value: "2"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-api-db-migration
  labels:
    app.kubernetes.io/name: test-api
    app.kubernetes.io/instance: test-api
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-30" # Syncs before other resources
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation # Delete job before creating a new one
spec:
  template:
    spec:
      containers:
      - name: test-api-db-migrate
        image: busybox
        command: ["sh", "-c", "sleep 5"]
        resources: {}
      restartPolicy: Never
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-api
  labels:
    app.kubernetes.io/instance: test-api
    app.kubernetes.io/name: test-api
  annotations:
    argocd.argoproj.io/sync-wave: "5" # Syncs before other resources
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-api
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
