apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-ref-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-ref-deployment
  template:
    metadata:
      labels:
        app: rollout-ref-deployment
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: rollout-ref-deployment
# spec:
#   replicas: 0
#   workloadRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: rollout-ref-deployment
#   strategy:
#     canary:
#       steps:
#         - setWeight: 20
#         - pause: {duration: 10s}
